# Generated by Django 2.0.4 on 2018-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('str_type', '文本'), ('image_type', '图片')], default='str_type', max_length=10, verbose_name='类型')),
                ('key_key', models.CharField(max_length=32, verbose_name='参数名')),
                ('key_value', models.CharField(max_length=128, null=True, verbose_name='参数值')),
                ('key_remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '参数设置',
                'verbose_name_plural': '参数设置',
                'db_table': 'xcx_parameter',
            },
        ),
    ]
