# Generated by Django 2.0.4 on 2018-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='key_remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='key_value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='参数值'),
        ),
    ]
